---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        #- image: ivantou/petclinic 
        - image: pcacr.azurecr.io/it-sz-petclinic:dev
          imagePullPolicy: Always
          name: petclinic
          ports:
            - containerPort: 8080
      restartPolicy: Always
