# This workflow will build a Java project with Maven, build a docker container and publish it to Azure Container Registry

name: Java CI with Maven and Azure

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Caching the Maven dependencies to speed up the workflow exection time
    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
   
    # Test and package the source code with Maven    
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - name: Package with Maven
      run: mvn -B package --file pom.xml -P MySQL -DskipTests=true

    # Move the application to the Dockerfile directory
    - name: Move the package to ./tomcat_petclinic/
      run: |
        mv ./target/petclinic.war ./tomcat_petclinic/petclinic.war

    # Connect to Azure Container Registry (ACR) 
    - name: Docker login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: pcacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        docker build ./tomcat_petclinic -t pcacr.azurecr.io/it-sz-petclinic
        docker tag pcacr.azurecr.io/it-sz-petclinic pcacr.azurecr.io/it-sz-petclinic:latest
        docker push pcacr.azurecr.io/it-sz-petclinic:latest
